### ISSUE TITLE
Földi AD mód nincs felkészítve a már előzetesen felvitt AAD felhasználókra

### ISSUE THREAD

**Issue by martonrideg** [sulikon/eKreta2SDS#17]
Eredeti specifikáció szerint üres AAD-vel kellett működni.
Azonban vannak helyek, ahol AAD-be már vettek fel tanárokat SDS-sel kezelve.
Ezekhez a felhasználókhoz most földi AD user létrehozását nem kezdeményezi.

**Comment by tiborkovacs-dev** [comment]
Ha ezt a kódrészletet kivesszük, vagy plusz kapcsolóval látjuk el (pl.: CheckADUsers) , akkor és a Local AD is aktív, akkor minden felhasználó bekerül a localAD....csv fájlba.

eKreta2SDS.psm1: ~640. sor

         if ($DomainName) {
                #LocalAD Mode
                if ($null -ne $global:azureadusers[$_.TeacherUsername]) {
                    # the user account exists in Azure AD.
                    $_.ADUserName = $_.TeacherUserName
                }
            } 
Ha bekerülnek a felhasználók a localAD csv fájlba, akkor a ott már meg van írva a kód, ami ellenőrzi, hogy létezik-e a felhasználó, vagy létre kell hozni.

**Comment by martonrideg** [comment]
OK, jó így! Egyben megoldja #20  - at is

**Comment by martonrideg** [comment]
Sajnos mégsem az igazi, akkor a 753-756-ot is el kell kapcsolóval látni a diákok miatt.
Akkor már talán elegánsabb a #20 alatt javasolt megoldás
